-- slurmdbdの実際のMySQLテーブルスキーマ
-- Source: SchedMD/slurm src/plugins/accounting_storage/mysql/accounting_storage_mysql.c
-- Cluster name: gpu_cluster

CREATE TABLE IF NOT EXISTS `tres_table` (
  `creation_time` bigint unsigned NOT NULL,
  `deleted`       tinyint NOT NULL DEFAULT 0,
  `id`            int NOT NULL AUTO_INCREMENT,
  `type`          tinytext NOT NULL,
  `name`          tinytext NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `udex` (`type`(42), `name`(42))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `tres_table` (`creation_time`, `id`, `type`, `name`) VALUES
(UNIX_TIMESTAMP(), 1, 'cpu', ''),
(UNIX_TIMESTAMP(), 2, 'mem', ''),
(UNIX_TIMESTAMP(), 3, 'energy', ''),
(UNIX_TIMESTAMP(), 4, 'node', ''),
(UNIX_TIMESTAMP(), 5, 'billing', ''),
(UNIX_TIMESTAMP(), 6, 'fs', 'disk'),
(UNIX_TIMESTAMP(), 7, 'vmem', ''),
(UNIX_TIMESTAMP(), 8, 'pages', ''),
(UNIX_TIMESTAMP(), 1001, 'gres', 'gpu');

CREATE TABLE IF NOT EXISTS `gpu_cluster_assoc_table` (
  `creation_time`       bigint unsigned NOT NULL,
  `mod_time`            bigint unsigned NOT NULL DEFAULT 0,
  `deleted`             tinyint NOT NULL DEFAULT 0,
  `comment`             text,
  `flags`               int unsigned NOT NULL DEFAULT 0,
  `is_def`              tinyint NOT NULL DEFAULT 0,
  `id_assoc`            int unsigned NOT NULL AUTO_INCREMENT,
  `user`                tinytext NOT NULL DEFAULT '',
  `acct`                tinytext NOT NULL,
  `partition`           tinytext NOT NULL DEFAULT '',
  `parent_acct`         tinytext NOT NULL DEFAULT '',
  `id_parent`           int unsigned NOT NULL DEFAULT 0,
  `lineage`             text,
  `shares`              int NOT NULL DEFAULT 1,
  `max_jobs`            int DEFAULT NULL,
  `max_jobs_accrue`     int DEFAULT NULL,
  `min_prio_thresh`     int DEFAULT NULL,
  `max_submit_jobs`     int DEFAULT NULL,
  `max_tres_pj`         text NOT NULL DEFAULT '',
  `max_tres_pn`         text NOT NULL DEFAULT '',
  `max_tres_mins_pj`    text NOT NULL DEFAULT '',
  `max_tres_run_mins`   text NOT NULL DEFAULT '',
  `max_wall_pj`         int DEFAULT NULL,
  `grp_jobs`            int DEFAULT NULL,
  `grp_jobs_accrue`     int DEFAULT NULL,
  `grp_submit_jobs`     int DEFAULT NULL,
  `grp_tres`            text NOT NULL DEFAULT '',
  `grp_tres_mins`       text NOT NULL DEFAULT '',
  `grp_tres_run_mins`   text NOT NULL DEFAULT '',
  `grp_wall`            int DEFAULT NULL,
  `priority`            int unsigned DEFAULT NULL,
  `def_qos_id`          int DEFAULT NULL,
  `qos`                 blob NOT NULL DEFAULT '',
  `delta_qos`           blob NOT NULL DEFAULT '',
  PRIMARY KEY (`id_assoc`),
  UNIQUE KEY `udex` (`user`(42), `acct`(42), `partition`(42))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `gpu_cluster_job_table` (
  `job_db_inx`          bigint unsigned NOT NULL AUTO_INCREMENT,
  `mod_time`            bigint unsigned NOT NULL DEFAULT 0,
  `deleted`             tinyint NOT NULL DEFAULT 0,
  `account`             tinytext,
  `admin_comment`       text,
  `array_task_str`      text,
  `array_max_tasks`     int unsigned NOT NULL DEFAULT 0,
  `array_task_pending`  int unsigned NOT NULL DEFAULT 0,
  `constraints`         text DEFAULT '',
  `container`           text,
  `cpus_req`            int unsigned NOT NULL DEFAULT 0,
  `derived_ec`          int unsigned NOT NULL DEFAULT 0,
  `derived_es`          text,
  `env_hash_inx`        bigint unsigned NOT NULL DEFAULT 0,
  `exit_code`           int unsigned NOT NULL DEFAULT 0,
  `extra`               text,
  `flags`               int unsigned NOT NULL DEFAULT 0,
  `failed_node`         tinytext,
  `job_name`            tinytext NOT NULL,
  `id_assoc`            int unsigned NOT NULL,
  `id_array_job`        int unsigned NOT NULL DEFAULT 0,
  `id_array_task`       int unsigned NOT NULL DEFAULT 4294967294,
  `id_block`            tinytext,
  `id_job`              int unsigned NOT NULL,
  `id_qos`              int unsigned NOT NULL DEFAULT 0,
  `id_resv`             int unsigned NOT NULL DEFAULT 0,
  `id_wckey`            int unsigned NOT NULL DEFAULT 0,
  `id_user`             int unsigned NOT NULL DEFAULT 0,
  `id_group`            int unsigned NOT NULL DEFAULT 0,
  `het_job_id`          int unsigned NOT NULL DEFAULT 0,
  `het_job_offset`      int unsigned NOT NULL DEFAULT 0,
  `kill_requid`         int unsigned DEFAULT NULL,
  `state_reason_prev`   int unsigned NOT NULL DEFAULT 0,
  `licenses`            text,
  `mcs_label`           tinytext DEFAULT '',
  `mem_req`             bigint unsigned NOT NULL DEFAULT 0,
  `nodelist`            text NOT NULL DEFAULT '',
  `nodes_alloc`         int unsigned NOT NULL DEFAULT 0,
  `node_inx`            text,
  `partition`           tinytext NOT NULL,
  `priority`            int unsigned NOT NULL DEFAULT 0,
  `qos_req`             text,
  `restart_cnt`         smallint unsigned DEFAULT 0,
  `resv_req`            text,
  `script_hash_inx`     bigint unsigned NOT NULL DEFAULT 0,
  `state`               int unsigned NOT NULL,
  `timelimit`           int unsigned NOT NULL DEFAULT 0,
  `time_submit`         bigint unsigned NOT NULL DEFAULT 0,
  `time_eligible`       bigint unsigned NOT NULL DEFAULT 0,
  `time_start`          bigint unsigned NOT NULL DEFAULT 0,
  `time_end`            bigint unsigned NOT NULL DEFAULT 0,
  `time_suspended`      bigint unsigned NOT NULL DEFAULT 0,
  `gres_used`           text NOT NULL DEFAULT '',
  `wckey`               tinytext NOT NULL DEFAULT '',
  `work_dir`            text NOT NULL DEFAULT '',
  `segment_size`        smallint unsigned NOT NULL DEFAULT 0,
  `std_err`             text NOT NULL DEFAULT '',
  `std_in`              text NOT NULL DEFAULT '',
  `std_out`             text NOT NULL DEFAULT '',
  `submit_line`         longtext,
  `system_comment`      text,
  `tres_alloc`          text NOT NULL DEFAULT '',
  `tres_req`            text NOT NULL DEFAULT '',
  PRIMARY KEY (`job_db_inx`),
  UNIQUE KEY `udex` (`id_job`, `time_submit`),
  KEY `old_tuple` (`id_job`, `id_assoc`, `time_submit`),
  KEY `rollup` (`time_eligible`, `time_end`),
  KEY `rollup2` (`time_end`, `time_eligible`),
  KEY `nodes_alloc` (`nodes_alloc`),
  KEY `wckey` (`id_wckey`),
  KEY `qos` (`id_qos`),
  KEY `association` (`id_assoc`),
  KEY `array_job` (`id_array_job`),
  KEY `het_job` (`het_job_id`),
  KEY `reserv` (`id_resv`),
  KEY `sacct_def` (`id_user`, `time_start`, `time_end`),
  KEY `sacct_def2` (`id_user`, `time_end`, `time_eligible`),
  KEY `env_hash_inx` (`env_hash_inx`),
  KEY `script_hash_inx` (`script_hash_inx`),
  KEY `archive_delete` (`deleted`),
  KEY `archive_purge` (`time_end`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `gpu_cluster_step_table` (
  `job_db_inx`          bigint unsigned NOT NULL,
  `deleted`             tinyint NOT NULL DEFAULT 0,
  `exit_code`           int NOT NULL DEFAULT 0,
  `id_step`             int NOT NULL,
  `step_het_comp`       int unsigned NOT NULL DEFAULT 4294967294,
  `kill_requid`         int unsigned DEFAULT NULL,
  `nodelist`            text NOT NULL DEFAULT '',
  `nodes_alloc`         int unsigned NOT NULL DEFAULT 0,
  `node_inx`            text,
  `state`               smallint unsigned NOT NULL DEFAULT 0,
  `step_name`           text NOT NULL DEFAULT '',
  `task_cnt`            int unsigned NOT NULL DEFAULT 0,
  `task_dist`           int NOT NULL DEFAULT 0,
  `time_start`          bigint unsigned NOT NULL DEFAULT 0,
  `time_end`            bigint unsigned NOT NULL DEFAULT 0,
  `time_suspended`      bigint unsigned NOT NULL DEFAULT 0,
  `timelimit`           int unsigned NOT NULL DEFAULT 0,
  `user_sec`            bigint unsigned NOT NULL DEFAULT 0,
  `user_usec`           int unsigned NOT NULL DEFAULT 0,
  `sys_sec`             bigint unsigned NOT NULL DEFAULT 0,
  `sys_usec`            int unsigned NOT NULL DEFAULT 0,
  `act_cpufreq`         double unsigned NOT NULL DEFAULT 0.0,
  `consumed_energy`     bigint unsigned NOT NULL DEFAULT 0,
  `container`           text,
  `req_cpufreq_min`     int unsigned NOT NULL DEFAULT 0,
  `req_cpufreq`         int unsigned NOT NULL DEFAULT 0,
  `req_cpufreq_gov`     int unsigned NOT NULL DEFAULT 0,
  `cwd`                 text NOT NULL DEFAULT '',
  `std_err`             text NOT NULL DEFAULT '',
  `std_in`              text NOT NULL DEFAULT '',
  `std_out`             text NOT NULL DEFAULT '',
  `submit_line`         longtext,
  `tres_alloc`          text NOT NULL DEFAULT '',
  `tres_usage_in_ave`   text NOT NULL DEFAULT '',
  `tres_usage_in_max`   text NOT NULL DEFAULT '',
  `tres_usage_in_max_taskid`  text NOT NULL DEFAULT '',
  `tres_usage_in_max_nodeid`  text NOT NULL DEFAULT '',
  `tres_usage_in_min`   text NOT NULL DEFAULT '',
  `tres_usage_in_min_taskid`  text NOT NULL DEFAULT '',
  `tres_usage_in_min_nodeid`  text NOT NULL DEFAULT '',
  `tres_usage_in_tot`   text NOT NULL DEFAULT '',
  `tres_usage_out_ave`  text NOT NULL DEFAULT '',
  `tres_usage_out_max`  text NOT NULL DEFAULT '',
  `tres_usage_out_max_taskid` text NOT NULL DEFAULT '',
  `tres_usage_out_max_nodeid` text NOT NULL DEFAULT '',
  `tres_usage_out_min`  text NOT NULL DEFAULT '',
  `tres_usage_out_min_taskid` text NOT NULL DEFAULT '',
  `tres_usage_out_min_nodeid` text NOT NULL DEFAULT '',
  `tres_usage_out_tot`  text NOT NULL DEFAULT '',
  PRIMARY KEY (`job_db_inx`, `id_step`, `step_het_comp`),
  KEY `archive_delete` (`deleted`),
  KEY `archive_purge` (`time_end`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
